name: personalsite-frontend # you probably want to 'snapcraft register <name>'
version: '0.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Personal site frontend server.       
description: |
  The server for personal site's frontend. Powered bt fbthrift and aws.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  frontend-server:
    command: frontend-server

  test-client:
    command: TestClient

parts:
  frontend:
    plugin: cmake
    source: https://github.com/amartya00/PersonalSiteFrontend.git

  aws-cpp-sdk-core:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/aws-cpp-sdk-core.tar

  aws-cpp-sdk-dynamodb:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/aws-cpp-sdk-dynamodb.tar

  boost-context:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/boost_context.tar

  boost-filesystem:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/boost_filesystem.tar

  boost-program-options:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/boost_program_options.tar

  boost-regex:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/boost_regex.tar

  boost-system:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/boost_system.tar

  boost-thread:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/boost_thread.tar

  double-conversion:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/double-conversion.tar

  event-2:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/event-2.tar

  folly:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/folly.tar

  gflags:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/gflags.tar

  glog:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/glog.tar

  icudata:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/icudata.tar

  icui18n:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/icui18n.tar

  icuuc:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/icuuc.tar

  jsoncpp:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/jsoncpp.tar

  snappy:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/snappy.tar

  stdc++:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/stdc%2B%2B.tar

  thrift:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/thrift.tar

  thriftcpp2:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/thriftcpp2.tar

  thriftfrozen2: 
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/thriftfrozen2.tar

  thriftprotocol:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/thriftprotocol.tar

  unwind:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/unwind.tar

  zstd:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/zstd.tar

  auth:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/auth.tar

  gapiwrapper:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/gapiwrapper.tar
