name: personalsite-frontend # you probably want to 'snapcraft register <name>'
version: '0.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Personal site frontend server.       
description: |
  The server for personal site's frontend. Powered bt fbthrift and aws.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  frontend-server:
    command: frontend-server

  test-client:
    command: TestClient

parts:
  frontend:
    plugin: cmake
    source: /home/amartya/Projects/PersonalSite/FrontEnd


  dependencies:
    plugin: cmake
    source: https://s3.amazonaws.com/amartya00-service-artifacts/personal-site/dependencies/dependencies.tar.gz
